#!/usr/bin/env node

const shella = require('shella');

async function buildDists() {
  const { stdout: lsStdout } = await shella({
    stdio: 'pipe',
  })`ls -d1 fixtures/src/*`;
  const srcs = lsStdout.split('\n');

  for (const src of srcs) {
    const dist = src.replace('/src/', '/dist/');
    console.info(`Building for ${src}`);
    await shella`./bin/check-env ${src} --outDir ${dist}`;
  }
}

async function typeCheckDists() {
  const { stdout: lsStdout } = await shella({
    stdio: 'pipe',
  })`ls -d1 fixtures/dist/*/*`;
  const dists = lsStdout.split('\n');

  for (const dist of dists) {
    console.info(`Type checking for ${dist}`);
    await shella`tsc --noEmit --project ${dist}`;
  }
}

(async () => {
  await buildDists();
  await typeCheckDists();
})();
